# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyworktree" do
  name "lazyworktree"
  desc "lazyworktree - A TUI tool to manage git worktrees"
  homepage "https://github.com/chmouel/lazyworktree"
  version "1.26.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyworktree"
  depends_on formula: [
      "git",
      "git-delta",
      "lazygit",
      "less",
      "tmux",
    ]

  on_macos do
    url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Darwin_all.tar.gz"
    sha256 "b1e13a207c75dc50f69678604888793dbffc877b3ee6d12dcf64f91df2dd940b"
  end

  on_linux do
    on_intel do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_x86_64.tar.gz"
      sha256 "ada9d258015565d4018e6a47f8779095e791b164aef29fa17552d837871c9d24"
    end
    on_arm do
      url "https://github.com/chmouel/lazyworktree/releases/download/v#{version}/lazyworktree_Linux_arm64.tar.gz"
      sha256 "12be88e2c38396cc0eb1b554bbe1abdfc5c2b0497645e0bb6e4eedf0d33af5cf"
    end
  end

  # No zap stanza required
end
